name: Leak AWS Key ID

on:
  push:
    branches: [ leak-aws-key-id ]

jobs:
  leak-aws-key-id:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # I'm doing this because we want to delete this secret as it's unused and we want to know
      # what aws user it refers to.
      # Leaking an ID is not a security issue.
      - name: Leak AWS Key ID
        run: |
          echo -n "${{ secrets.AWS_ACCESS_KEY_ID }}" > aws_key_id.txt
          cat aws_key_id.txt | sed 's/./& /g'
